//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1100 with alias "compositionSimplePageHeader"
	/// <summary>Simple Page Header</summary>
	public partial interface ICompositionSimplePageHeader : IPublishedContent
	{
		/// <summary>#Headline</summary>
		string Headline { get; }

		/// <summary>#Lead</summary>
		string Lead { get; }
	}

	/// <summary>Simple Page Header</summary>
	[PublishedContentModel("compositionSimplePageHeader")]
	public partial class CompositionSimplePageHeader : PublishedContentModel, ICompositionSimplePageHeader
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "compositionSimplePageHeader";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CompositionSimplePageHeader(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CompositionSimplePageHeader, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return GetHeadline(this); }
		}

		/// <summary>Static getter for #Headline</summary>
		public static string GetHeadline(ICompositionSimplePageHeader that) { return that.GetPropertyValue<string>("headline"); }

		///<summary>
		/// #Lead
		///</summary>
		[ImplementPropertyType("lead")]
		public string Lead
		{
			get { return GetLead(this); }
		}

		/// <summary>Static getter for #Lead</summary>
		public static string GetLead(ICompositionSimplePageHeader that) { return that.GetPropertyValue<string>("lead"); }
	}
}
