//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>GenericPage</summary>
	[PublishedContentModel("GenericPage")]
	public partial class GenericPage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "GenericPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GenericPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GenericPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #Witten By
		///</summary>
		[ImplementPropertyType("author")]
		public string Author
		{
			get { return this.GetPropertyValue<string>("author"); }
		}

		///<summary>
		/// #Date
		///</summary>
		[ImplementPropertyType("date")]
		public DateTime Date
		{
			get { return this.GetPropertyValue<DateTime>("date"); }
		}

		///<summary>
		/// #Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return this.GetPropertyValue<string>("headline"); }
		}

		///<summary>
		/// #Image
		///</summary>
		[ImplementPropertyType("heroImage")]
		public string HeroImage
		{
			get { return this.GetPropertyValue<string>("heroImage"); }
		}

		///<summary>
		/// #Image Text
		///</summary>
		[ImplementPropertyType("imageText")]
		public string ImageText
		{
			get { return this.GetPropertyValue<string>("imageText"); }
		}

		///<summary>
		/// #Lead
		///</summary>
		[ImplementPropertyType("lead")]
		public string Lead
		{
			get { return this.GetPropertyValue<string>("lead"); }
		}

		///<summary>
		/// #Tag
		///</summary>
		[ImplementPropertyType("tagPicker")]
		public IEnumerable<IPublishedContent> TagPicker
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("tagPicker"); }
		}

		///<summary>
		/// #Trompet
		///</summary>
		[ImplementPropertyType("trompet")]
		public string Trompet
		{
			get { return this.GetPropertyValue<string>("trompet"); }
		}
	}
}
